# Generated by Django 4.0.6 on 2022-09-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='employees/%Y/%m/%d')),
                ('mail', models.CharField(db_index=True, max_length=200)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(db_index=True, max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('image1', models.ImageField(blank=True, upload_to='estates/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='estates/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, upload_to='estates/%Y/%m/%d')),
                ('area', models.DecimalField(decimal_places=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=20)),
                ('description', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estates', to='agency.employee')),
            ],
            options={
                'verbose_name': 'estate',
                'verbose_name_plural': 'estates',
                'ordering': ('name',),
            },
        ),
    ]
